[package]
name = "amelio"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "GPL"
description = "Amelio - A university project for the IUBH"
homepage = "https://amelio.dnaka91.rocks"
repository = "https://github.com/dnaka91/amelio"
documentation = "https://github.com/dnaka91/amelio"

[dependencies]
anyhow = "1.0.28"
askama = { version = "0.9.0", features = ["with-rocket"] }
ctrlc = { version = "3.1.4", features = ["termination"] }
diesel = { version = "1.4.4", features = ["r2d2", "sqlite"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
envy = "0.4.1"
libsqlite3-sys = { version = "0.17.3", features = ["bundled"] }
log = { version = "0.4.8", features = ["release_max_level_info"] }
rocket = "0.4.4"
serde = { version = "1.0.106", features = ["derive"] }

[profile.release]
lto = true
panic = "abort"
