[package]
name = "amelio"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "GPL"
description = "Amelio - A university project for the IUBH"
homepage = "https://amelio.dnaka91.rocks"
repository = "https://github.com/dnaka91/amelio"
documentation = "https://github.com/dnaka91/amelio"
build = "build.rs"

[dependencies]
anyhow = "1.0.28"
askama = { version = "0.9.0", features = ["with-rocket"] }
bcrypt = "0.8.0"
ctrlc = { version = "3.1.4", features = ["termination"] }
diesel = { version = "1.4.4", features = ["r2d2", "sqlite"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
envy = "0.4.1"
lettre_email = "0.9.4"
libsqlite3-sys = { version = "0.17.3", features = ["bundled"] }
log = { version = "0.4.8", features = ["release_max_level_info"] }
native-tls = { version = "0.2.4", features = ["vendored"] }
phf = "0.8.0"
rand = "0.7.3"
rocket = "0.4.4"
rust-embed = "5.5.1"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
strum = { version = "0.18.0", features = ["derive"] }
toml = "0.5.6"

[dependencies.lettre]
version = "0.9.3"
default-features = false
features = ["smtp-transport"]

[build-dependencies]
hex = "0.4.2"
phf_codegen = "0.8.0"
sha-1 = "0.8.2"
walkdir = "2.3.1"

[profile.release]
lto = true
panic = "abort"
