name: Docs
on:
  push:
    branches:
      - master
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
      - name: Add redirect
        run: echo '<meta http-equiv="refresh" content="0;url=amelio/index.html">' > target/doc/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
